# aliases
alias vim=nvim                                  # let's use nvim
alias ll="ls -lahG"                              # list all file, human-readable sizes, with colors
alias retmux="tmux attach-session -t $1"        # `tmux a ` is just not enough
alias cp="cp -i"                                # Confirm before overwriting something
alias df='df -h'                                # Human-readable sizes


