# aliases
alias vim=nvim                                  # let's use nvim
alias ll="ls -lahG"                              # list all file, human-readable sizes, with colors
alias retmux="tmux attach-session -t $1"        # `tmux a ` is just not enough
alias cp="cp -i"                                # Confirm before overwriting something
alias df='df -h'                                # Human-readable sizes
alias pyv='source venv/bin/activate'            # source virtualenv from root of project
alias mkvenv="python3 -m venv venv --prompt=$1" # create virtualenv with directory venv

# save history between sessions
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
SAVEHIST=10000
HISTSIZE=5000
# share history across multiple zsh sessions
setopt SHARE_HISTORY
# append to history
setopt APPEND_HISTORY

# expire duplicates first
setopt HIST_EXPIRE_DUPS_FIRST 
# do not store duplications
setopt HIST_IGNORE_DUPS
#ignore duplicates when searching
setopt HIST_FIND_NO_DUPS
# removes blank lines from history
setopt HIST_REDUCE_BLANKS



# Created by `pipx` on 2021-06-23 19:35:17
export PATH="$PATH:/Users/bi01043261/.local/bin"
