# python
export PYTHONSTARTUP=~/.pythonstartup
export PACKAGECLOUD_MASTER_TOKEN=


# agrible schema locations
export AS_DIR=~/PycharmProjects/agrible-schema
source ~/PycharmProjects/agrible-schema/as-docker.sh

# agrible mfr locations
export MFR_DIR=~/PycharmProjects/morningfarmreport
export PDAPI_DIR=~/PycharmProjects/product-data-api
# This should be using MFG_DIR

# source project related directories
source $AS_DIR/as-docker.sh
source $MFR_DIR/mfr-docker.sh
source $PDAPI_DIR/pd-docker.sh

# source local env variables 
source ~/.zshenv.local
